server.address=0.0.0.0
server.port=${PORT:10000}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
telegram.chat-id=${TELEGRAM_CHAT_ID:}
telegram.webhook-secret=${WEBHOOK_SECRET:}
